import scrapy
from selenium import webdriver
import pandas as pd
import csv

def scrapy_usdebtclock():
    DRIVER_PATH = '/path/to/chromedriver'
    driver = webdriver.Chrome(executable_path=r"C:\chromedriver\chromedriver.exe") 
    driver.get('https://www.usdebtclock.org/')
    data_list = []
    accountant = 1
    flag = True
    while flag == True:
        data = driver.find_elements_by_xpath('//div[@id="layer{}"]'.format(accountant))
        for p in range(len(data)):
            if(data[p].text != ''):
                data_list.append(data[p].text)
        accountant = accountant + 1
        if(accountant == 438):
            flag = False

    number = ['US NATIONAL DEBT', 'DEBT PER CITIZEN', 'DEBT PER TAXPAYER', 'US FEDERAL SPENDING(OFFICIAL)', 'US FEDERAL BUGGET DEFICIT(OFFICIAL)', 'MEDICARE/MEDICAID', 'SOCIAL SECURITY',
    'DEFENSE/WAR', 'US TOTLA DEBT', 'US POPULATION', 'US WORKFORCE NOW', 'OFFICIAL UNEMPLOYED', 'US INCOME TAXPAYERS', 'US WORKFORCE 2000*', 'ACTUAL UNEMPLOYED', 'PRIVATE SECTOR JOBS',
    'NOT IN LABOR FORCE NOW', 'FULL-TIME WORKERS', 'US SELF-EMPLOYED', 'NOT IN LABOR FORCE 2000*', 'PART-TIME WORKERS', 'US GROSS DEMESTIC PRODUCT', 'NOW', 'TOTAL FEDERAL/STATE/LOCAL SPENDING',
    'SPENDING TO GDP RATIO', 'US FEDERAL TAX REVENUE', 'REVENUE PER CITIZEN', 'INCOME TAX REVENUE', 'PAYROLL TAX REVENUE', 'CORPORATE TAX REVENUE', 'US M2 MONEY SUPPLY NOW', 
    'CURRENCY AND CREDIT DERIVATIVES NOW', 'US DEBT HELD BY FOREING COUNTRIES', 'US TRADE DEFICIT', 'US IMPORTED OIL', 'TOTAL STATE REVENUE', 'STATE DEBT', 'TOTAL LOCAL REVENUE', 'LOCAL DEBT', 
    'TOTAL PERSONAL DEBT', 'CREDIT CARD DEBT', 'STUDENT LOAN DEBT', 'US UNION WORKERS', 'MEDICAL NEW NOME NOW', 'MEDICAL INCOME NOW', 'GOVERNMENT ENPLOYEES', 'MEDICAL NEW NOME 2000', 
    'MEDICAL INCOME 2000*', 'MANUFACTURING JOBS NOW', 'US BANKRUPTCIES', 'MANUFACTURING JOBS 2000*', 'US FORECLOSURES', 'US RETIREES', 'US DISABLED', 'LIVING IN POVERTY', 'MEDICARE EMROLLEES',
    'FOOD STAMP RECIPIENTS', 'WITHOUT INSUFANCE', 'MEDICAID RECIPIENTS', 'US TOTAL NATIONAL ASSETS', 'ASSETS PER CITIZEN', 'US UNFUNDED LIABILITIES', 'INTEREST ON DEBT(NET)', 
    'US TOTAL INTEREST PAID', 'SAVINGS PER FAMILY', 'PERSONAL DEBT PER CIT.', 'US M2 MONEY SUPPLY 2000', 'CURRENCY ABD CREDIT DERIVATIVES 2000', 'US TRADE  DEFICIT - CHINA', 'HOUSEHOLD ASSETS',
    'SOCIAL SECURITY LIABILITY', 'MEDICARE LIABILITY', 'PAPER TO SILVER RATIO NOW', 'PAPER TO GOLD RATIO NOW', 'DOLLAR TO OIL RATIO NOW', 'DOLLAR TO OIL RATIO 1913', 'DOLLAR TO SILVER RATIO NOW',
    'DOLLAR TO SILVER RATIO 1913', 'DOLLAR TO GOLD RATIO NOW', 'DOLLAR TO GOLD RATIO 1913', 'US FEDERAL SPENDING (ACTUAL)', 'US FEDERAL BUDGET DEFICIT (ACTUAL)', '1960', '1980', '2000', 
    'TARIFF TAX REVENUE', 'STATE DEBT PER CITIZEN', 'LOCAL DEBT PER CITIZEN', 'BANK INTEREST RECIEVED', 'BANK INTEREST PAID', 'INTEREST PER ADULT', 'PER STUDENT', 'PER HOLDER', 
    'DOLLAR TO CRIPTO RATIO NOW', 'DOLLAR TO CRIPTO RATIO 2013', 'US MILLIONAIRES', 'TOTAL DEBT TO GDP RATIO', 'LIABILITY PER CITIZEN', 'US TREASURY DOLLARS NOW']
    df = pd.DataFrame(data = data_list, index = number)
    print(df)
    df.to_csv('data.csv')

scrapy_usdebtclock()